import { AiFillStar } from "react-icons/ai";
import camera from '../../../assets/camera.png'
const data = [
  {
    img: "https://i.postimg.cc/cHgcX5zQ/nike.png",
    title: "Nike Air Monarch IV",
    owner: "Rohit Richards",
    OldNew: 'New',
    desiredProduct: "Sony Camera",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    likes: "153",
    newPrice: "5999",
    company: "Nike",
    color: "white",
    category: "sneakers",
  },
  {
    img: camera,
    title: "Sony Camera Digital",
    owner: "Ram Shinde",
    OldNew: 'Old',
    desiredProduct: "Apple Watch Series 7/8",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    likes: "153",
    newPrice: "1999",
    company: "U S POLO",
    color: "white",
    category: "T-shirt",
  },
  {
    img: "https://i.postimg.cc/cHgcX5zQ/nike.png",
    title: "Nike Air Monarch IV",
    owner: "Rohit Richards",
    OldNew: 'New',
    desiredProduct: "Sony Camera",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    likes: "153",
    newPrice: "5999",
    company: "Nike",
    color: "white",
    category: "sneakers",
  },
  {
    img:camera,
    title: "Sony Camera Digital",
    owner: "Ram Shinde",
    OldNew: 'Old',
    desiredProduct: "Apple Watch Series 7/8",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    likes: "153",
    newPrice: "1999",
    company: "U S POLO",
    color: "white",
    category: "T-shirt",
  },
  {
    img: "https://i.postimg.cc/cHgcX5zQ/nike.png",
    title: "Nike Air Monarch IV",
    owner: "Rohit Richards",
    OldNew: 'New',
    desiredProduct: "Sony Camera",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    likes: "153",
    newPrice: "5999",
    company: "Nike",
    color: "white",
    category: "sneakers",
  },
  {
    img:camera,
    title: "Sony Camera Digital",
    owner: "Ram Shinde",
    OldNew: 'Old',
    desiredProduct: "Apple Watch Series 7/8",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    likes: "153",
    newPrice: "1999",
    company: "U S POLO",
    color: "white",
    category: "T-shirt",
  },
  {
    img: "https://i.postimg.cc/cHgcX5zQ/nike.png",
    title: "Nike Air Monarch IV",
    owner: "Rohit Richards",
    OldNew: 'New',
    desiredProduct: "Sony Camera",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    likes: "153",
    newPrice: "5999",
    company: "Nike",
    color: "white",
    category: "sneakers",
  },
  {
    img:camera,
    title: "Sony Camera Digital",
    owner: "Ram Shinde",
    OldNew: 'Old',
    desiredProduct: "Apple Watch Series 7/8",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    likes: "153",
    newPrice: "1999",
    company: "U S POLO",
    color: "white",
    category: "T-shirt",
  },
  {
    img: "https://i.postimg.cc/cHgcX5zQ/nike.png",
    title: "Nike Air Monarch IV",
    owner: "Rohit Richards",
    OldNew: 'New',
    desiredProduct: "Sony Camera",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    likes: "153",
    newPrice: "5999",
    company: "Nike",
    color: "white",
    category: "sneakers",
  },
  {
    img:camera,
    title: "Sony Camera Digital",
    owner: "Ram Shinde",
    OldNew: 'Old',
    desiredProduct: "Apple Watch Series 7/8",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    likes: "153",
    newPrice: "1999",
    company: "U S POLO",
    color: "white",
    category: "T-shirt",
  },
  {
    img: "https://i.postimg.cc/cHgcX5zQ/nike.png",
    title: "Nike Air Monarch IV",
    owner: "Rohit Richards",
    OldNew: 'New',
    desiredProduct: "Sony Camera",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    likes: "153",
    newPrice: "5999",
    company: "Nike",
    color: "white",
    category: "sneakers",
  },
  {
    img:camera,
    title: "Sony Camera Digital",
    owner: "Ram Shinde",
    OldNew: 'Old',
    desiredProduct: "Apple Watch Series 7/8",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    likes: "153",
    newPrice: "1999",
    company: "U S POLO",
    color: "white",
    category: "T-shirt",
  },
  {
    img: "https://i.postimg.cc/cHgcX5zQ/nike.png",
    title: "Nike Air Monarch IV",
    owner: "Rohit Richards",
    OldNew: 'New',
    desiredProduct: "Sony Camera",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    likes: "153",
    newPrice: "5999",
    company: "Nike",
    color: "white",
    category: "sneakers",
  },
  {
    img:camera,
    title: "Sony Camera Digital",
    owner: "Ram Shinde",
    OldNew: 'Old',
    desiredProduct: "Apple Watch Series 7/8",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    likes: "153",
    newPrice: "1999",
    company: "U S POLO",
    color: "white",
    category: "T-shirt",
  },
  
];

export default data;
