import { AiFillStar } from "react-icons/ai";

const data = [
  {
    img: "https://i.postimg.cc/cHgcX5zQ/nike.png",
    title: "Nike Air Monarch IV",
    owner: "Rohit Richards",
    OldNew: 'New',
    desiredProduct: "Sony Camera",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    likes: "153",
    newPrice: "5999",
    company: "Nike",
    color: "white",
    category: "sneakers",
  },
  {
    img: "https://o.remove.bg/downloads/b5ae25fa-eba6-40df-a7c9-0700b362da2d/pngtree-camera-digital-slr-electronics-png-image_5279952-removebg-preview.png",
    title: "Sony Camera Digital",
    owner: "Ram Shinde",
    OldNew: 'Old',
    desiredProduct: "Apple Watch Series 7/8",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    likes: "153",
    newPrice: "1999",
    company: "U S POLO",
    color: "white",
    category: "T-shirt",
  },
  {
    img: "https://i.postimg.cc/cHgcX5zQ/nike.png",
    title: "Nike Air Monarch IV",
    owner: "Rohit Richards",
    OldNew: 'New',
    desiredProduct: "Sony Camera",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    likes: "153",
    newPrice: "5999",
    company: "Nike",
    color: "white",
    category: "sneakers",
  },
  {
    img: "https://o.remove.bg/downloads/b5ae25fa-eba6-40df-a7c9-0700b362da2d/pngtree-camera-digital-slr-electronics-png-image_5279952-removebg-preview.png",
    title: "Sony Camera Digital",
    owner: "Ram Shinde",
    OldNew: 'Old',
    desiredProduct: "Apple Watch Series 7/8",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    likes: "153",
    newPrice: "1999",
    company: "U S POLO",
    color: "white",
    category: "T-shirt",
  },
  {
    img: "https://i.postimg.cc/cHgcX5zQ/nike.png",
    title: "Nike Air Monarch IV",
    owner: "Rohit Richards",
    OldNew: 'New',
    desiredProduct: "Sony Camera",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    likes: "153",
    newPrice: "5999",
    company: "Nike",
    color: "white",
    category: "sneakers",
  },
  {
    img: "https://o.remove.bg/downloads/b5ae25fa-eba6-40df-a7c9-0700b362da2d/pngtree-camera-digital-slr-electronics-png-image_5279952-removebg-preview.png",
    title: "Sony Camera Digital",
    owner: "Ram Shinde",
    OldNew: 'Old',
    desiredProduct: "Apple Watch Series 7/8",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    likes: "153",
    newPrice: "1999",
    company: "U S POLO",
    color: "white",
    category: "T-shirt",
  },
  {
    img: "https://i.postimg.cc/cHgcX5zQ/nike.png",
    title: "Nike Air Monarch IV",
    owner: "Rohit Richards",
    OldNew: 'New',
    desiredProduct: "Sony Camera",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    likes: "153",
    newPrice: "5999",
    company: "Nike",
    color: "white",
    category: "sneakers",
  },
  {
    img: "https://o.remove.bg/downloads/b5ae25fa-eba6-40df-a7c9-0700b362da2d/pngtree-camera-digital-slr-electronics-png-image_5279952-removebg-preview.png",
    title: "Sony Camera Digital",
    owner: "Ram Shinde",
    OldNew: 'Old',
    desiredProduct: "Apple Watch Series 7/8",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    likes: "153",
    newPrice: "1999",
    company: "U S POLO",
    color: "white",
    category: "T-shirt",
  },
  {
    img: "https://i.postimg.cc/cHgcX5zQ/nike.png",
    title: "Nike Air Monarch IV",
    owner: "Rohit Richards",
    OldNew: 'New',
    desiredProduct: "Sony Camera",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    likes: "153",
    newPrice: "5999",
    company: "Nike",
    color: "white",
    category: "sneakers",
  },
  {
    img: "https://o.remove.bg/downloads/b5ae25fa-eba6-40df-a7c9-0700b362da2d/pngtree-camera-digital-slr-electronics-png-image_5279952-removebg-preview.png",
    title: "Sony Camera Digital",
    owner: "Ram Shinde",
    OldNew: 'Old',
    desiredProduct: "Apple Watch Series 7/8",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    likes: "153",
    newPrice: "1999",
    company: "U S POLO",
    color: "white",
    category: "T-shirt",
  },
  {
    img: "https://i.postimg.cc/cHgcX5zQ/nike.png",
    title: "Nike Air Monarch IV",
    owner: "Rohit Richards",
    OldNew: 'New',
    desiredProduct: "Sony Camera",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    likes: "153",
    newPrice: "5999",
    company: "Nike",
    color: "white",
    category: "sneakers",
  },
  {
    img: "https://o.remove.bg/downloads/b5ae25fa-eba6-40df-a7c9-0700b362da2d/pngtree-camera-digital-slr-electronics-png-image_5279952-removebg-preview.png",
    title: "Sony Camera Digital",
    owner: "Ram Shinde",
    OldNew: 'Old',
    desiredProduct: "Apple Watch Series 7/8",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    likes: "153",
    newPrice: "1999",
    company: "U S POLO",
    color: "white",
    category: "T-shirt",
  },
  {
    img: "https://i.postimg.cc/cHgcX5zQ/nike.png",
    title: "Nike Air Monarch IV",
    owner: "Rohit Richards",
    OldNew: 'New',
    desiredProduct: "Sony Camera",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    likes: "153",
    newPrice: "5999",
    company: "Nike",
    color: "white",
    category: "sneakers",
  },
  {
    img: "https://o.remove.bg/downloads/b5ae25fa-eba6-40df-a7c9-0700b362da2d/pngtree-camera-digital-slr-electronics-png-image_5279952-removebg-preview.png",
    title: "Sony Camera Digital",
    owner: "Ram Shinde",
    OldNew: 'Old',
    desiredProduct: "Apple Watch Series 7/8",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    likes: "153",
    newPrice: "1999",
    company: "U S POLO",
    color: "white",
    category: "T-shirt",
  },
  
];

export default data;
